##
# SCSS Lint
# guide - https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
##

## Stylesheet directory
scss_files: './app/styles/**/*.scss'

## Default severity
severity: error

## Linters
linters:

  # Reports when you use improper spacing around ! (the "bang") in !default, !global, !important, and !optional flags.
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # Reports when a BEM selector contains more elements than a configurable maximum number.
  BemDepth:
    enabled: true
    max_elements: 1

  # Prefer the terser border: 0 over border: none, as it is usually what is intended.
  BorderZero:
    enabled: true
    convention: zero

  # Reports when you define a rule set using a selector with chained classes (a.k.a. adjoining classes).
  ChainedClasses:
    enabled: true

  # Prefer hexadecimal color codes over color keywords.
  ColorKeyword:
    enabled: true

  # Prefer color literals (keywords or hexadecimal codes) to be used only in variable declarations.
  ColorVariable:
    enabled: true

  # Prefer loud comments '/** **/' over silent '//'
  Comment:
    enabled: false
    style: loud

  # Warn if there are any left over '@debug' statements
  DebugStatement:
    severity: warning
    enabled: true

  # Rule sets should be ordered as follows: @extend declarations, @include declarations without inner @content, properties, @include declarations with inner @content, then nested rule sets.
  DeclarationOrder:
    enabled: false

  # scss-lint:disable control comments should be preceded by a comment explaining why these linters are being disabled for this file.
  DisableLinterReason:
    enabled: true

  # Reports when you define the same property twice in a single rule set.
  DuplicateProperty:
    enabled: true

  # Place @else statements on the same line as the preceding curly brace.
  ElsePlacement:
    enabled: true
    style: same_line

  # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # Empty rules should be removed
  EmptyRule:
    enabled: true

  # Reports when you have an @extend directive.
  ExtendDirective:
    enabled: false

  # Files should always have a final newline.
  FinalNewline:
    enabled: true
    present: true

  # Colour hex should be full 6 characters
  HexLength:
    enabled: true
    style: long

  # Hex notation, whether it's uppercase or lowercase (uppercase preferred).
  HexNotation:
    enabled: true
    style: uppercase

  # Ensure hexadecimal colors are valid (either three or six digits).
  HexValidation:
    enabled: true

  # Avoid using ID selectors.
  IdSelector:
    enabled: true

  # Avoid using !important in properties. It is usually indicative of a misunderstanding of CSS specificity and can lead to brittle code.
  ImportantRule:
    enabled: true

  # The base names of @imported SCSS partials should not begin with an underscore and should not include the filename extension.
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  # Use four spaces per indentation level.
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  # Don't write leading zeros for numeric values with a decimal point.
  LeadingZero:
    enabled: true
    style: exclude_zero

  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    force_nesting: true

  # Name format of selectors
  # TODO - Set a good standard for BEM syntax.
  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  # Avoid nesting selectors too deeply.
  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: false

  # Enforces that functions, mixins, and variables that follow the private naming convention (default to underscore-prefixed, e.g. $_foo) are defined and used within the same file.
  PrivateNamingConvention:
    enabled: false
    prefix: _

  # Limit the number of properties in a rule set.
  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  # Sort properties in a strict order.
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order: ["position", "top", "right", "bottom", "left", "z-index", "display", "visibility", "overflow", "overflow-x", "overflow-y", "float", "clear", "table-layout", "border-collapse", "empty-cells", "box-sizing", "width", "min-width", "max-width", "height", "min-height", "max-height", "margin", "margin-top", "margin-right", "margin-bottom", "margin-left", "padding", "padding-top", "padding-right", "padding-bottom", "padding-left", "border", "border-width", "border-style", "border-color", "border-radius", "border-top", "border-top-width", "border-top-style", "border-top-color", "border-right", "border-right-width", "border-right-style", "border-right-color", "border-bottom", "border-bottom-width", "border-bottom-style", "border-bottom-color", "border-left", "border-left-width", "border-left-style", "border-left-color", "border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius", "white-space", "content", "color", "background", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-size", "opacity", "font", "font-weight", "font-style", "font-variant", "font-size", "font-family", "letter-spacing", "line-height", "list-style", "list-style-type", "list-style-position", "list-style-image", "outline", "outline-width", "outline-style", "outline-color", "text-align", "text-decoration", "text-indent", "text-transform", "text-shadow", "animation", "transform", "transition", "box-shadow"]

  # Reports when you use an unknown or disabled CSS property (ignoring vendor-prefixed properties).
  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []

  # Configure which units are allowed for property values.
  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  # Pseudo-elements, like ::before, and ::first-letter, should be declared with two colons. Pseudo-classes, like :hover and :first-child, should be declared with one colon.
  PseudoElement:
    enabled: true

  # Avoid qualifying elements in selectors (also known as "tag-qualifying").
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  # Don't write selectors with a depth of applicability greater than 3.
  SelectorDepth:
    enabled: true
    max_depth: 3

  # It is good practice to choose a convention for naming selectors.
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # Split selectors onto separate lines after each comma, and have each individual selector occupy a single line.
  SingleLinePerSelector:
    enabled: true

  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  # Comment literals should be followed by a space.
  SpaceAfterComment:
    enabled: false
    style: one_space # or 'no_space', or 'at_least_one_space'
    allow_empty_comments: true

  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true

  # Variables should be formatted with a single space separating the colon from the variable's value.
  SpaceAfterVariableColon:
    enabled: false
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  # Variables should be formatted with no space between the name and the colon.
  SpaceAfterVariableName:
    enabled: true

  # Operators should be formatted with a single space on both sides of an infix operator. These include +, -, *, /, %, ==, !=, >, >=, <, and <=.
  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # String literals should be written with single quotes unless using double quotes would save on escape characters.
  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  # Property values; @extend, @include, and @import directives; and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true

  # Reports lines containing trailing whitespace.
  TrailingWhitespace:
    enabled: true

  # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: false

  # Don't use the all keyword to specify transition properties.
  TransitionAll:
    enabled: true

  # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true

  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true

  # URLs should be valid and not contain protocols or domain names.
  UrlFormat:
    enabled: true

  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true

  # Properties, like color and font, are easier to read and maintain when defined using variables rather than literals.
  VariableForProperty:
    enabled: true
    properties: [
      'color',
      'font'
    ]

  # Avoid vendor prefixes. That is, don't write them yourself.
  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: [
      '-ms-text-size-adjust',
      '-webkit-text-size-adjust'
    ]

  # Omit length units on zero values.
  ZeroUnit:
    enabled: true